name: KeepHerokuAlive

# Controls when the action will run. 
on:
  # Cron job
  schedule:
    - cron: '0,15,30,45 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  keepalive:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        env:
            HEROKU_URL: ${{ secrets.HEROKU_URL }}
        run: curl "$HEROKU_URL"
